version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: fotoalbum_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    environment:
      - DOCKER_ENV=true
    volumes:
      - ./uploads:/app/uploads
      - backend_node_modules:/app/node_modules
    user: "1000:1000"
    networks:
      - app-network


  frontend:
    build:
      context: ./frontend
    container_name: fotoalbum_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  backend_node_modules:
  