
services:
  backend:
    build:
      context: ./backend
    container_name: fotoalbum_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    environment:
      - DOCKER_ENV=true
      - NODE_ENV=development
    volumes:
      - ./uploads:/app/uploads
      - backend_node_modules:/app/node_modules
    user: "1000:1000"
    networks:
      - app-network

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
    container_name: fotoalbum_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge

volumes:
  backend_node_modules: